parameters = {
    'temporal_nli_test': {
        'filename': 'temporal_nli_test.csv',
        'random_seed': True,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 40,
    },
    'temporal_nli_simple_event_names_train': {
        'filename': 'temporal_nli_simple_event_names_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_simple_event_names_test': {
        'filename': 'temporal_nli_simple_event_names_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 40,
    },
    'temporal_nli_all_diff_train': {
        'filename': 'temporal_nli_all_diff_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_same_english_train': {
        'filename': 'temporal_nli_same_english_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_same_names_train': {
        'filename': 'temporal_nli_same_names.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_same_structures_train': {
        'filename': 'temporal_nli_same_structures_train.csv',
        'random_seed': True,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_same_structures_and_templates_train': {
        'filename': 'temporal_nli_same_structures_and_templates_train.csv',
        'random_seed': True,
        'names': 'train_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_before_after_train': {
        'filename': 'temporal_nli_before_after_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'after'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_only_before_sort_train': {
        'filename': 'temporal_nli_only_before_sort_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'after'],
        'sort_relationships': True,
        'count': 150,
    },
    'temporal_nli_only_before_sort_test': {
        'filename': 'temporal_nli_only_before_sort_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after'],
        'sort_relationships': True,
        'count': 40,
    },
    'temporal_nli_only_before_train': {
        'filename': 'temporal_nli_only_before_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'after'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_only_before_test': {
        'filename': 'temporal_nli_only_before_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after'],
        'sort_relationships': False,
        'count': 40,
    },
    'temporal_nli_before_after_test': {
        'filename': 'temporal_nli_before_after_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'after'],
        'sort_relationships': False,
        'count': 40,
    },
    'temporal_nli_before_simultaneous_train': {
        'filename': 'temporal_nli_before_simultaneous_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['before', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_before_simultaneous_test': {
        'filename': 'temporal_nli_before_simultaneous_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['before', 'simultaneous'],
        'sort_relationships': False,
        'count': 40,
    },
    'temporal_nli_after_simultaneous_train': {
        'filename': 'temporal_nli_after_simultaneous_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['after', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'temporal_nli_after_simultaneous_test': {
        'filename': 'temporal_nli_after_simultaneous_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['after', 'simultaneous'],
        'sort_relationships': False,
        'count': 40,
    },
    'temporal_nli_sort_relationships_train': {
        'filename': 'temporal_nli_sort_relationships_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'templates': 'train',
        'domain': 'temporal',
        'relationship_types': ['after', 'before', 'simultaneous'],
        'sort_relationships': True,
        'count': 150,
    },
    'temporal_nli_sort_relationships_test': {
        'filename': 'temporal_nli_sort_relationships_test.csv',
        'random_seed': False,
        'names': 'test_event_names',
        'templates': 'test',
        'domain': 'temporal',
        'relationship_types': ['after', 'before', 'simultaneous'],
        'sort_relationships': True,
        'count': 40,
    },
    'spatial_nli_test': {
        'filename': 'spatial_nli_relationships_test.csv',
        'random_seed': False,
        'names': 'test_event_place_names',
        'templates': 'test',
        'domain': 'spatial',
        'relationship_types': ['after', 'before', 'simultaneous'],
        'sort_relationships': False,
        'count': 40,
    },
    'spatial_nli_train': {
        'filename': 'spatial_nli_relationships_train.csv',
        'random_seed': False,
        'names': 'train_event_place_names',
        'templates': 'train',
        'domain': 'spatial',
        'relationship_types': ['after', 'before', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'logical_nli_train': {
        'filename': 'logical_nli_relationships_train.csv',
        'random_seed': False,
        'names': 'simple_events_train_names',
        'templates': 'train',
        'domain': 'logical',
        'relationship_types': ['after', 'before', 'simultaneous'],
        'sort_relationships': False,
        'count': 150,
    },
    'logical_nli_test': {
        'filename': 'logical_nli_relationships_test.csv',
        'random_seed': False,
        'names': 'simple_events_test_names',
        'templates': 'test',
        'domain': 'logical',
        'relationship_types': ['after', 'before', 'simultaneous'],
        'sort_relationships': False,
        'count': 40,
    },
    'logical_only_before_sorted_nli_train': {
        'filename': 'logical_only_before_sorted_nli_train.csv',
        'random_seed': False,
        'names': 'train_event_names',
        'names': 'simple_events_train_names',
        'domain': 'logical',
        'relationship_types': ['after', 'before'],
        'sort_relationships': True,
        'count': 150,
    },
    'logical_only_before_sorted_nli_test': {
        'filename': 'logical_only_before_sorted_nli_test.csv',
        'random_seed': False,
        'names': 'simple_events_test_names',
        'templates': 'test',
        'domain': 'logical',
        'relationship_types': ['after', 'before'],
        'sort_relationships': True,
        'count': 40,
    }
}